

dic = {'Physical Review' : 'Phys. Rev.',
       'Physical Review Letters' : 'Phys. Rev. Lett.', 
       'Physical Review A' : 'Phys. Rev. A',
       'Physical Review B' : 'Phys. Rev. B',
       'Physical Review E' : 'Phys. Rev. E',
       'Physical Review Research' : 'Phys. Rev. Res.',
       'The Journal of Chemical Physics' : 'J. Chem. Phys.',
       'WIREs Computational Molecular Science' : 'Wiley Interdiscip. Rev.: Comput. Mol. Sci.',
       'Journal of Chemical Theory and Computation' : 'J. Chem. Theory Comput.',
       'International Journal of Quantum Chemistry' : 'Int. J. Quantum Chem.',
       'Annals of Physics' : 'Ann. Phys.',
       'SIAM Journal on Matrix Analysis and Applications' : 'SIAM J. Matrix Anal. Appl.',
       'SIAM Journal on Numerical Analysis' : 'SIAM J. Numer. Anal.',
       'SIAM Journal on Scientific Computing' : 'SIAM J. Sci. Comput.',
       'Chemical Physics' : 'Chem. Phys.',
       'International Journal of Modern Physics B' : 'Int. J. Mod. Phys. B',
       'Chemical Physics Letters' : 'Chem. Phys. Lett.',
       'Chemical Reviews' : 'Chem. Rev.',
       'Journal of Physics B: Atomic, Molecular and Optical Physics' : 'J. Phys. B',
       'Science' : 'Science',
       'Optics Communications' : 'Opt. Commun.',
       'Optics Express' : 'Opt. Express',
       'Journal of Physics: Conference Series' : 'J. Phys.: Conf. Ser.',
       'The Journal of Physical Chemistry Letters' : 'J. Phys. Chem. Lett.',
       'The Journal of Physical Chemistry' : 'J. Phys. Chem.',
       'The Journal of Physical Chemistry A' : 'J. Phys. Chem. A',
       'Molecular Physics' : 'Mol. Phys.',
       'Journal of the American Chemical Society' : 'J. Am. Chem. Soc.',
       'Physics Reports' : 'Phys. Rep.',
       'Journal of Computational Physics' : 'J. Comput. Phys.',
       'Journal of Computational Chemistry' : 'J. Comput. Chem.',
       'New Journal of Physics' : 'New J. Phys.',
       'ACM Transactions on Mathematical Software' : 'ACM Trans. Math. Softw.',
       'ChemPhysChem' : 'Chem. Phys. Chem.',
       'Annual Review of Physical Chemistry' : 'Annu. Rev. Phys. Chem.',
       'Nature communications' : 'Nat. Commun.',
       'Frontiers in Chemistry' : 'Front. Chem.',
       'The European Physical Journal D' : 'Eur. Phys. J. D',
       'SciPost Phys. Lect. Notes' : 'SciPost Phys. Lect. Notes',
       'The European Physical Journal Special Topics' : 'Eur. Phys. J.: Spec. Top.',
       'Phys. Chem. Chem. Phys.' : 'Phys. Chem. Chem. Phys.',
       'Mass Spectrometry Reviews' : 'Mass Spectrom. Rev.',
       'Journal of the American Society for Mass Spectrometry' : 'J. Am. Soc. Mass Spectrom.',
       'Zeitschrift für Physikalische Chemie' : 'Z. Phys. Chem.',
       'Applied Mathematics Research eXpress' : 'Appl. Math. Res. Express',
       'Philosophical Transactions of the Royal Society A: ' +
          'Mathematical, Physical and Engineering Sciences' : 'Philos. Trans. R. Soc.',
       'Faraday Discuss.' : 'Faraday Discuss.',
       'Nature Reviews Chemistry' : 'Nat. Rev. Chem.',
       'Central European Journal of Physics' : 'Cent. Eur. J. Phys.',
       'IEEE Journal of Selected Topics in Quantum Electronics' : 'IEEE J. Sel. Top. Quantum Electron.',
       'Reviews of Modern Physics' : 'Rev. Mod. Phys.',
       'Laser Physics' : 'Laser Phys.',
       'Journal of Modern Optics' : 'J. Mod. Opt.'
       }






